<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="BIL-PC" name="com.epam.calculator.testCalculator.engineerOperations.TestCos" tests="1" failures="0" timestamp="31 May 2016 22:34:05 GMT" time="0.001" errors="1">
  <testcase name="testCosPassDouble" time="0.001" classname="com.epam.calculator.testCalculator.engineerOperations.TestCos">
    <error type="java.lang.AssertionError" message="error in cos() expected [0.5403023058681398] but found [0.8414709848078965]">
      <![CDATA[java.lang.AssertionError: error in cos() expected [0.5403023058681398] but found [0.8414709848078965]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at com.epam.calculator.testCalculator.engineerOperations.TestCos.testCosPassDouble(TestCos.java:23)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
]]>
    </error>
  </testcase> <!-- testCosPassDouble -->
</testsuite> <!-- com.epam.calculator.testCalculator.engineerOperations.TestCos -->
